### ISSUE TITLE
Handle collisions

### ISSUE THREAD

**Issue by kvsari** [kvsari/derive-getters#5]
See if I can detect methods on the struct that share the same name as the struct element and ignore code generation.

**Comment by Arnavion** [comment]
This is not possible with proc macros.

Edit: An alternative is to let the user add a field attribute `#[getters(ignore)]` that suppresses that field's getter.

**Comment by kvsari** [comment]
Righto, thanks for the tip @Arnavion .

**Comment by kvsari** [comment]
Done.
