### ISSUE TITLE
Consider removing the `get_` prefix from generated functions

### ISSUE THREAD

**Issue by LukasKalbertodt** [kvsari/derive-getters#8]
Using `get_` in names of getter functions is rather unidiomatic in Rust. Source:

- [API guidelines C-GETTER](https://rust-lang-nursery.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter)
- [RFC 344: naming conventions](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis)

It would be great if this library could be changed to generate idiomatic getter functions :)

**Comment by kvsari** [comment]
Thanks for the tip!

**Comment by kvsari** [comment]
Working on new version in issue8 branch.

**Comment by kvsari** [comment]
Done. Version 0.0.5 published.
